functionsDirectory = "/Users/lucky/Desktop/hhhhhh/netlify/functions"
functionsDirectoryOrigin = "default"
plugins = []
headers = []

[build]
publish = "/Users/lucky/Desktop/hhhhhh"
publishOrigin = "default"
functions = "/Users/lucky/Desktop/hhhhhh/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/products.json"
to = "/.netlify/functions/products"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]